<a href="https://colab.research.google.com/github/msandhiya07/Weatherdb/blob/main/Weatherdb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("/content/weather_forecast_data.csv")
df.head()

Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1    27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2    25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3    23.622080  74.367758    7.050551    67.255282   982.632013     rain
4    20.591370  96.858822    4.643921    47.676444   980.825142  no rain

In [4]:
df.shape

(2500, 6)

In [5]:
df.index

RangeIndex(start=0, stop=2500, step=1)

In [6]:
df.columns

Index(['Temperature', 'Humidity', 'Wind_Speed', 'Cloud_Cover', 'Pressure',
       'Rain'],
      dtype='object')

In [8]:
df.dtypes

Temperature    float64
Humidity       float64
Wind_Speed     float64
Cloud_Cover    float64
Pressure       float64
Rain            object
dtype: object

#unique()

In [9]:
df["Cloud_Cover"].unique()

array([50.50169383,  4.99005293, 14.85578394, ..., 75.84295207,
        2.37874275, 81.357508  ])

In [11]:
df["Temperature"].unique()

array([23.7203376 , 27.87973416, 25.0690844 , ..., 28.10827448,
       14.78927534, 26.55435586])

In [12]:
df["Wind_Speed"].unique()

array([ 7.33560439,  5.95248359,  1.37199182, ...,  2.89712751,
        2.37471725, 18.56308397])

In [13]:
df["Rain"].unique()

array(['rain', 'no rain'], dtype=object)

In [14]:
df.nunique()

Temperature    2500
Humidity       2500
Wind_Speed     2500
Cloud_Cover    2500
Pressure       2500
Rain              2
dtype: int64

In [15]:
df.count()

Temperature    2500
Humidity       2500
Wind_Speed     2500
Cloud_Cover    2500
Pressure       2500
Rain           2500
dtype: int64

In [16]:
df["Rain"].value_counts()

Rain
no rain    2186
rain        314
Name: count, dtype: int64

In [17]:
df["Humidity"].value_counts()

Humidity
89.592641    1
58.119033    1
65.730672    1
46.055473    1
43.864233    1
            ..
69.363734    1
48.604141    1
73.864573    1
99.464287    1
97.101517    1
Name: count, Length: 2500, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  2500 non-null   float64
 1   Humidity     2500 non-null   float64
 2   Wind_Speed   2500 non-null   float64
 3   Cloud_Cover  2500 non-null   float64
 4   Pressure     2500 non-null   float64
 5   Rain         2500 non-null   object 
dtypes: float64(5), object(1)
memory usage: 117.3+ KB
